### ISSUE TITLE
XEP-0045 Multi-User Chat: Enable create, join and direct invites to a room

### ISSUE THREAD

**Issue by rasos** [monal-im/Monal#41]
Users expect today an easy way to create a room and to invite or simply add their colleagues or family members. Monal (as well as ChatSecure) only show rooms, that are already available. For a seamless user experience iOS users do not want to go back to their desktop or a web based xmpp client, to create or manage rooms. 

Do we have a chance to get more of MUC administration features as specified in XEP-0045 integrated in Monal?

**Comment by benjaminbischoff** [comment]
And also it would be helpful to integrate autojoin like conversations and a better user interface to join a room

**Comment by Echolon** [comment]
https://xmpp.org/extensions/xep-0045.html

**Comment by Echolon** [comment]
Someone (:man_shrugging:) tagged this XEP as :heavy_check_mark: in the XEP overview list. Is that appropriate? Or are main features missing?

https://github.com/anurodhp/Monal/edit/develop/XEPsupport.md

@anurodhp 
@tmolitor-stud-tu

**Comment by anurodhp** [comment]
This should be working

**Comment by Echolon** [comment]
@rasos I will close this. If there are specific issues with that, please create a new issue. Thank you!

**Comment by tmolitor-stud-tu** [comment]
But the muc management features (add user to group or remove user from group as well as promoting a member to be administrator/owner) is not implemented, right?

And that seems to be what @rasos asked for.

**Comment by tmolitor-stud-tu** [comment]
join, mediated invites and direct invites are implemented now, muc creation and muc management features still missing, though.

Thus I'm keeping this open.

**Comment by tmolitor-stud-tu** [comment]
implemented now, thanks @FriedrichAltheide :)
